env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - plugin:react-redux/recommended
overrides: [ ]
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'react-redux'
  - 'react-hooks'
  - 'vildan'

rules:
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/ban-ts-ignore': off
  "object-curly-spacing":
    - error
    - always
  "react/jsx-tag-spacing":
    - error
    - beforeSelfClosing: always
  react/prop-types: 'off'
  react/display-name: 'off'
  vildan/path-checker:
    - 'error'
    - alias: '@'
