env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - plugin:react-redux/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - 'react'
  - '@typescript-eslint'
  - 'react-redux'
  - 'react-hooks'
  - 'vildan'
  - 'unused-imports'
  - 'import'
rules:
  unused-imports/no-unused-imports:
    - error
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  "react/jsx-max-props-per-line":
    - error
    - maximum: 2
      when: multiline
  "@typescript-eslint/no-namespace": off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/ban-ts-ignore': off
  "object-curly-spacing":
    - error
    - always
  "react/jsx-tag-spacing":
    - error
    - beforeSelfClosing: always
  react/prop-types: 'off'
  react/display-name: 'off'
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: react
          group: external
          position: before
        - pattern: '@/**'
          group: external
          position: after
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  vildan/path-checker:
    - 'error'
    - alias: '@'
  vildan/public-api:
    - 'error'
    - alias: '@'
      ignoreImportPatterns: [ '**/*.test.*', '**/*.story.*', '**/StoreDecorator.tsx' ]
  vildan/layer-imports:
    - 'error'
    - alias: '@'
      ignoreImportPatterns: [ '**/StoreProvider', '**/testing', '**/routeConfig.tsx']
overrides:
- files:
  - '**/src/**/*.{test,stories}.{ts,tsx}'
  rules:
    i18next/no-literal-string: off
    max-len: off
    import/no-default-export: off
